name: s3 deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: us-east-1

      - name: npm install
        run: npm i

      - name: build
        run: STAGE=dev npm run build

      - name: copy files to s3
        run: aws s3 cp ./build  s3://part-tape-actions-to-s3

      - name: Invalidate cache
        run: |
          aws cloudfront create-invalidation \
          --distribution-id E1RXXVAFP32ZBB \
          --paths "/*"
